### ISSUE TITLE
[Bug] Type definition of .toThrowWithMessage() is broken

### ISSUE THREAD

**Issue by sounisi5011** [jest-community/jest-extended#472]
**Bug**

- `package` version: [`jest-extended@3.0.1`](https://github.com/jest-community/jest-extended/tree/v3.0.1)
- `node` version: 16.16.0 or 14.19.3 (This bug is caused by a TypeScript type definition and has nothing to do with the Node.js version)
- `pnpm` version: 6.33.0

Relevant code

```ts
expect(() => {
  throw TypeError('hello world');
}).toThrowWithMessage(TypeError, 'hello world');

expect.toThrowWithMessage(TypeError, 'hello world');
```

What you did:

I used TypeScript's `tsc` command to check for the presence of errors caused by type definitions in the test code.

What happened (please provide anything you think will help):

Due to [a change](https://github.com/jest-community/jest-extended/pull/471/files#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccceR390) introduced in #471, the constructor function cannot be specified as the first argument of toThrowWithMessage. If tried, the following error will be thrown:

```
error TS2345: Argument of type 'TypeErrorConstructor' is not assignable to parameter of type '(...args: unknown[]) => unknown'.
  Types of parameters 'message' and 'args' are incompatible.
    Type 'unknown' is not assignable to type 'string | undefined'.

3 }).toThrowWithMessage(TypeError, 'hello world');
                        ~~~~~~~~~
```

```
error TS2345: Argument of type 'TypeErrorConstructor' is not assignable to parameter of type '(...args: unknown[]) => unknown'.
  Types of parameters 'message' and 'args' are incompatible.
    Type 'unknown' is not assignable to type 'string | undefined'.

5 expect.toThrowWithMessage(TypeError, 'hello world');
                            ~~~~~~~~~
```

[TS Playground link](https://www.typescriptlang.org/play?ts=4.7.2#code/CYUwxgNghgTiAEYD2A7AzgF3hpAVAFjEgO4DqAlhvgLIhppQDmIAXPABQYCeADqxwDohsRmjYBXFAGsUJFAG0AugEp4AXgB88STLkAaeAFs6DZm0wxyKRvAA+8AEohGAUQAePVZvgA3JOWAAbgBYACgwnAIiMkoaEyYQdlxeEBcYIhgDAHJ8EAgIJHhiJBgIYCzlQKA)

---

Do not use `(...args: unknown[]) => unknown` in the type definition of an argument that can be passed any function.
This type requires that the function passed as an argument must be able to accept arguments of type `unknown`.
However, arguments of type `unknown` cannot be passed to [error constructor functions](https://github.com/microsoft/TypeScript/blob/v4.7.4/lib/lib.es5.d.ts#L1035), etc.
Use `(...args: any[]) => unknown` instead.

Or, given the [internal process](https://github.com/jest-community/jest-extended/blob/80d4ec55b50c5ff38c081e0bad2a7cdc0a3ad18e/src/matchers/toThrowWithMessage.js#L88-L92), `new (message: string) => unknown` seems appropriate.

Note: The truly correct type is `new (message: string | RegExp) => unknown`. However, when fixed to this type, we cannot specify the constructor function of the Error object. Perhaps this is a bug in `.toThrowWithMessage()`, but the Error object constructor function in Node.js works even if a RegExp is passed to the `message` argument, so I don't think there is any hurry to fix it.

**Comment by kayahr** [comment]
So when will this fix be published in a v3.0.2 for example? All my projects use jest-extended and it's a bit annoying to always exclude it from updating dependencies to prevent running into this compilation error.
