### ISSUE TITLE
Typescript error when importing jest-extended

### ISSUE THREAD

**Issue by ilyub** [jest-community/jest-extended#367]
**Bug**

jest-extended version: 1.0.0

.ts file:
```ts
import * as matchers from "jest-extended";
```

I get error:
File '.../node_modules/jest-extended/types/index.d.ts' is not a module.

Also, after upgrading to 1.0.0 unassigned import does not work any more:
```ts
import "jest-extended";
```

So:
Unassigned import stoped working in version 1.0.0
And wildcard import does not work in typescript because of invalid .d.ts file.

**Comment by abc-moviestarplanet** [comment]
I have the same issue too. My tests used to run fine when doing:
```typescript
import "jest-extended"
```

But after updating to v1.0.0, every function I used gives me the error such as:
```
expect(...).toBeEmpty is not a function".
```

I tried the full typescript setup as documented (using global.d.ts, include), but did not help.

**Comment by revmischa** [comment]
I tried every option here and on the TS setup in the docs with v1.0.0 and I also get `foo.test.ts:95:20 - error TS2339: Property 'toIncludeAllPartialMembers' does not exist on type 'JestMatchers...`

**Comment by idan-at** [comment]
[here ](https://github.com/jest-community/jest-extended/pull/370) is a fix for that specific missing type

**Comment by replete** [comment]
![Screen Shot 2021-10-29 at 23 22 49](https://user-images.githubusercontent.com/812139/139508105-392e8e42-4d5c-43ff-8df9-93c005674e79.png)

My workaround for this is as follows:
#### in `setupTests.ts`
```ts 
// @ts-ignore
import matchers from 'jest-extended/all'
expect.extend(matchers)
```
#### In my tests that use a `jest-extended` matcher:
```ts
// @ts-ignore
expect(res.body).toContainKey('users')
// @ts-ignore
expect(res.body.users[0]).toContainKeys(['_id', 'name', 'email', 'role', 'createdAt'])
```

I'm hoping that this gets fixed in this awesome-looking library in the next version, shouldn't be too difficult

**Comment by codejedi365** [comment]
I found a better solution for Typescript detection of types and project organization and integration with `ts-jest`.  First, I do not recommend adding the `jest-extended` types reference to `globals.d.ts` with the rest of your project.  This does not separate your tests from your source code and if you emit declaration files or other compiled files, it might include `jest` types.  Additionally, if you happen to have a type that overlaps with `jest-extended` then your Typescript will not warn you that your type is not declared when it really references a `jest-extended` type.

Instead, what you should do is create a `tsconfig.jest.json` extension file specifically for `ts-jest`.  This is similar to the extension files used for `eslint`, when you want to lint your test files but they are not included in your `src` directory.  

This [Gist](https://gist.github.com/codejedi365/f6a1115aa822b73cdc4475f46d179f83) provides the contents and description for my recommended configuration.

**Comment by replete** [comment]
Thanks for the fine recommendation and explanation, @codejedi365. Sounds like you could easily fix the root issue in this relatively new project. I'm still quite new to TypeScript, so using `// @ts-ignore` was a quick fix, and one that assumes that soon the root cause would be fixed anyway.

Cheers

**Comment by codejedi365** [comment]
not a problem, @replete, thanks for the compliment. My apologies as it seems I came "off the top rope" on your comment. I was trying to make a point for all others in the channel but I don't think it came off that way as I re-read.  My apologies. 

Yes, `@ts-ignore` is a quick fix when you don't know what to do and it's easy to feel that way when jumping into Typescript.  I remember it was about a year ago today when I first started TS. Recommend read, read, and read all the theory behind it (Medium.com has some helpful articles) and keep tinkering with it until you find how to make the compiler happy and work for you.

I'm hoping my Gist post does solve the most of the issues here, I was thankful it worked after hours of messing with it. I think the complexity of Typescript configurations is most to blame and the unknown need of all of us to update our jest config to the new naming convention used by this library.  If there is a root issue that needs fixing, I might have time in a few weeks.

**Comment by replete** [comment]
Using this now, I get intellisense in vscode, and my tests don't need `// @ts-ignore`

### setupTests.ts
```typescript
// @ts-ignore
import matchers from 'jest-extended/all'
expect.extend(matchers)
```

### existing ./tsconfig.json
```json
{
	
	"files": ["node_modules/jest-extended/types/index.d.s"]
}
```

**Comment by replete** [comment]
@ilyub Does the solution in [comment above](#issuecomment-955876805) solve your problem?

**Comment by replete** [comment]
@mattphillips I'm not super familiar with this library, or jest, but it seems to me like adding [this](#issuecomment-955876805) to the `README.md` somewhere would be useful for people running Typescript projects.

Unless this is only happening because of a bug? I am fairly new to typescript. If I knew it made sense I'd have just made a quick PR to update the README.

**Comment by codejedi365** [comment]
@deuscapturus can you provide more details? Post a link to a Gist that you upload the relevant files, and I'll take a look. Based on your error message it looks like you are importing types directly and that is likely going to have issues.

In the meantime, I recommend reviewing my post above with the Gist link.

**Comment by merrywhether** [comment]
This was my fix:
```
// tsconfig.json
  "include": [
    ...
    "setupTestsAfterEnv.ts"
  ],
```
// jest.config.js
  ...
  setupFilesAfterEnv: ['./setupTestsAfterEnv.ts'],
  ...
```

```ts
// setupTestsAfterEnv.ts

// import main for types, /all for auto-registration
import 'jest-extended';
import 'jest-extended/all';
```

Importing `jest-extended` is all TS needs to get it to register the types, and you only have to import it once in your project. This does not however cause anything JS-related to actually happen, and you can't really work with the exports of `jest-extended` because they aren't in the type defs.

Importing `jest-extended/all` causes the auto-registration of all of the matchers, but doesn't do anything types-wise. TS will allow un-typed imports like that though, since the side-effects aren't modeled in TS's type system.

A bit of bummer to need the two imports, but it's easier than other solutions.

**Comment by codejedi365** [comment]
@merrywhether, how are you compiling your distribution code?

I don't recommend adding your setup.ts file to `tsconfig.json[include]` because if you set the outdir, for tsconfig, it will include that file into your distribution. Unless you are using webpack or another bundler that uses your entrypoint for workflow. A distribution that has your setup ts file that isn't directly referenced isn't valuable but it is a random irrelevant piece of code in your build.

This is why I recommend a `tsconfig.jest.json` which extends your base taconfig but does not directly effect your real build configuration.

To clarify,what actually imports the types for `jest-extended` in your solution is your `tsconfig.json[include]`. The TS compiler evaluates included files and when accessing the setup file it sees the import statements so it follows them and finds the types.  It is not the import at jest runtime.

**Comment by merrywhether** [comment]
Good callout on the distribution config, as ours is not standard:
- `tsconfig.json` for dev work like type-checking tests/etc and integrating with IDEs (via default file-naming convention)
- `tsconfig.build.json` which extends `tsconfig.json` but excludes tests/etc

We also use babel for actual compilation (beyond type generation), so there's a lot of custom stuff going on that I should've specified. But it was late and I'd spent a bunch of time trying other fixes in the package to see if there was an easy PR; those all would've required a similar setup or restructuring of the package (TS does not make it easy to type raw imports without resorting to relying on have adjacent type files). 😄 

As far as what actually imports the types, it is definitely the `import 'jest-extended'` line (commenting that out gives me type errors again). It is technically a combination of doing that import in a file that TS is aware via the include, but without an import TS won't ever load the types for the library (we do the same thing for `jest-enzyme` as well, though its main import auto-executes).

**Comment by igorwessel** [comment]
A solution to this problem would be to move the type part to the DefinitelyTyped repo.
This would eliminate the problem of having to import twice, once for the types and once to register the matchers.

I can create a pull-request to add the types to DefinitelyTyped repo.

**Comment by igorwessel** [comment]
Hi guys!

To resolve the issue of being able to do the named import even though it doesn't cause a runtime issue, the problem is in declaration file don't have named exports for jest-extended module.
[types/index.d.ts](https://github.com/jest-community/jest-extended/blob/9cc3b9148c45d8f0143ea0c77a4cf30002f2fb6b/types/index.d.ts)

We can resolve adding each matcher to a module and exports.

```ts
declare module "jest-extended" {
	 /**
     * Use .toBeEmpty when checking if a String '', Array [], Object {} or Iterable (i.e. Map, Set) is empty.
     */
    toBeEmpty(): jest.CustomMatcherResult;
}
```

But we have a problem, I couldn't figure out how to make typescript just import the types into the imported method and merge with jest types, e.g:

```ts
import { toBeEmpty } from 'jest-extended';

expect.extend({
	toBeEmpty,
});
```

This will still import all matchers types and merge with jest.

**Comment by igorwessel** [comment]
I managed to make the typings for the typescript work when we only use some matchers.
First I separated the declaration from two matchers and add in own folder of respective matcher.
```ts
//@file: types/index.d.ts
declare namespace jest {
  // noinspection JSUnusedGlobalSymbols
  interface Matchers<R> {
    /**
     * Note: Currently unimplemented
     * Passing assertion
     *
     * @param {String} message
     */
    pass(message: string): R;
   ...
  }
}
```
moved to src/matchers/pass/index.d.ts:
```ts
// @file: src/matchers/pass/index.d.ts <- not need this line
/// <reference types="jest" />

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Note: Currently unimplemented
       * Passing assertion
       *
       * @param {String} message
       */
      pass(message?: string): never;
    }
    interface Expect {
      /**
       * Note: Currently unimplemented
       * Passing assertion
       *
       * @param {String} message
       */
      pass(message?: string): void;
    }
  }
}

export declare function pass(expected: string, message?: string): jest.CustomMatcherResult;
```

And use in setup.ts
```ts
import { pass } from 'jest-extended/dist/matchers/pass'

expect.extend({
  pass
})

@file: tsconfig.json
{
  ...,
  include: ["./setup.ts", ...]
}
```

With this we can import only the declaration of this specific file, without importing everything else.

I believe that it is currently impossible to have exports named with the jest matcher, why if we use for example the strategy of re-exporting all files in an index.js, and import only we need, typescript will follow all the re-exported files and find the declaration files (*.d.ts), which will have method typing that you didn't import.

I believe it is better to remove the named exports.

**Comment by mattphillips** [comment]
Hey all I've just opened #407 with an example project that demos how to setup `jest-extended` globally with Typescript.

Please let me know if this resolves the issues.

_Note:_ From what I can tell there is a separate issue / confusion around manually importing the matchers and the types lining up. I think it may be worth separating this into a different issue.

**Comment by igorwessel** [comment]
> Hey all I've just opened #407 with an example project that demos how to setup `jest-extended` globally with Typescript.
> 
> Please let me know if this resolves the issues.
> 
> _Note:_ From what I can tell there is a separate issue / confusion around manually importing the matchers and the types lining up. I think it may be worth separating this into a different issue.

Can I create this issue regarding this issue? or did some maintainer move this part to a new issue?

**Comment by mattphillips** [comment]
@igorwessel go for it 👍

**Comment by shahinghasemi** [comment]
My work around: 
`jest.config.js`:
```
{ ...
  setupFilesAfterEnv: ['jest-extended/all']
...}
```
then created a new file called `types/global.d.ts` and put `import 'jest-extended'` into it then **added it to the tsconfig file**: 
```
...
  "files": ["types/global.d.ts"],
...
```
Now typescript/vscode can find the types for intellisense.

**Comment by robinzimmermann** [comment]
Thanks for taking the time to post this, @shahinghasemi, your solution worked great for me!

**Comment by xenoterracide** [comment]
why is this such a pain with this library? I don't have problems with other libraries including generally just the jest types, this seems like a real issue still, using 3.0.1

it's not clear how to use a `jest.config.ts` with `ts-jest`, it's also not clear why this isn't a "module". Isn't there a fix that can be put into this library?

**Comment by xenoterracide** [comment]
I'm using yarn with pnp, ts-jest, and a jest-config.ts, not sure if anything else is relevent, but if sinon-chai for example can do this without significant configuration, then this doesn't impossible

**Comment by xenoterracide** [comment]
one thing I see different in the code between the sinon-chai definitely typed and this is

```
/// <reference types="chai" />
/// <reference types="sinon" />

import * as Sinon from 'sinon';

declare global {

    export namespace Chai {
...
```
vs just

```
/// <reference types="jest" />

declare namespace jest {
```

I'm going to play with this localy to see if it matters

**Comment by xenoterracide** [comment]
answers here may also be relevant (sorry for the comment spam, work firewall) https://stackoverflow.com/q/57132428/206466

**Comment by keeganwitt** [comment]
I'm thinking of removing that import.

One of the complications is `@types/jest` vs the built-in types in Jest and working with both.

**Comment by xenoterracide** [comment]
yeah, I'm not using `@types/jest` IIRC, peoples aren't supposed to be?

**Comment by xenoterracide** [comment]
after doing some more experimentation and thinking, I would think the file would need to have

```ts
import { MockInstance } from 'jest-mock'

declare module '@jest/globals' { ...
```

haven't gotten that working yet either though.

**Comment by xenoterracide** [comment]
can we reopen this regarding `@jest/globals`? because as far as I can see this jest-extended can't possibly work with that

**Comment by mattphillips** [comment]
@xenoterracide have you tried the example setup outlined in #407?

**Comment by xenoterracide** [comment]
@mattphillips yes, in what world do you think that will work with `@jest/globals`? the use case for which is to import the globals into your test file.

```
import { beforeEach, describe, expect, jest, test } from '@jest/globals'
```

**Comment by mattphillips** [comment]
@xenoterracide  I really don’t like the way you are choosing to communicate on this issue and the confrontational language being used - I’d ask you to show a little more respect when asking for help.

I’ve read your comments and am still none the wiser what you’re trying to do, what version of jest you’re using or the issue you’re actually having. So far you’ve just mentioned various technologies that have nothing to do with this project. For us to be able to help you, you would need to write a clear issue of your problem with plenty of context and ideally attach a repro (a repository containing a reproduction of the issue as close to your setup as possible).

FYI in the event you cannot reframe from a negative response, please feel free to click the fork button at the top of this repo and solve your problem yourself and maintain a fork.

**Comment by xenoterracide** [comment]
[`@jest/globals` is part of jest](https://jestjs.io/docs/api) it's the way jest itself is supporting types. 

```
├─ @cof/e1-devexchange-client@workspace:packages/devexchange-client
│  └─ jest@npm:28.1.3 [aec87] (via npm:^28.1.3 [aec87])
│
├─ @cof/e1-devexchange-client@workspace:packages/devexchange-client
│  └─ @jest/globals@npm:28.1.3 (via npm:^28.1.3)
└─ @cof/e1-transient-fault-handler@workspace:packages/transient-fault-handler
   └─ jest-extended@npm:3.0.1 [d67c0] (via npm:^3.0.1 [d67c0])
```


## System:
 - OS: macOS 11.6.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
## Binaries:
 - Node: 16.14.2 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-2c31da68/node
 - Yarn: 3.2.1 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-2c31da68/yarn
 - npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm

**Comment by xenoterracide** [comment]
```
└─ @cof/e1-transient-fault-handler@workspace:packages/transient-fault-handler
   └─ @types/jest@npm:28.1.6 (via npm:^28.1.6)
```

**Comment by xenoterracide** [comment]
```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "target": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "lib": ["es2018"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "baseUrl": ".",
    "module": "CommonJS",
    "allowJs": false,
    "checkJs": false,
    "noImplicitAny": true,
    "declarationMap": true,
    "strict": true,
    "skipLibCheck": false,
    "strictNullChecks": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "exclude": ["**/node_modules", "**/dist", "**/.test"],
  "files": []
}
```

**Comment by keeganwitt** [comment]
@xenoterracide Is what you are saying that if you don't use `@types/jest`, then when you try to do

```typescript
import { expect, test } from '@jest/globals';

import * as matchers from 'jest-extended';
expect.extend(matchers);
```

Then the import `from 'jest-extended'` fails with something like

```
File 'C:/Users/Keegan/Documents/Projects/jest-extended_ts-jest_test/node_modules/jest-extended/types/index.d.ts' is not a module.ts(2306)
```

in VS Code?

**Comment by xenoterracide** [comment]
@keeganwitt well firstly, I don't think `@types/jest` should be a thing anymore, just FYI. It just supplies what jest is doing right now, yes? so it seems like it should be replaced. Also, it's possible, and/or it's possible I couldn't figure out how to even make that happen correctly with `ts-jest`. I can try that again tomorrow to see why I couldn't make that happen if you'd like. I do feel like importing `jest-extended` into every file is not going to be great.

**Comment by keeganwitt** [comment]
I'll just mention I use ts-jest with @types/jest all the time without importing jest-extended into every file, but that is using `setupFilesAfterEnv`. If that's not working for you, there very well could be a misconfiguration in your project.

As for the usage of @types/jest in general. Eventually, yes, I think it will go away. But I'm not sure that's recommended just yet.

**Comment by xenoterracide** [comment]
It's recommended by jest, see the first sentence of that documentation.

**Comment by xenoterracide** [comment]
Also my problem is the test won't compile... Because it doesn't recognize the extra matchers. It'd be great if the problem was runtime.

**Comment by keeganwitt** [comment]
I was thinking of https://jestjs.io/docs/getting-started#type-definitions. I'm not sure which page you're referring to. If you don't want compile time checks of your tests, don't use ts-jest.

**Comment by cannontrodder** [comment]
After much frustration and experimentation with the above, I found I only had to add the package and then add:

```
"setupFilesAfterEnv": ["jest-extended/all"],
```
to my jest config in package.json and then **restarting vscode**

Without the last step, you play a game of whack-a-mole with the various different errors above and the suggested fixes.

**Comment by Codex-** [comment]
Opened #559 to resolve the original error.

**Comment by ngouy** [comment]
On my end my issue was I wasn't adding the `"setupFilesAfterEnv": ["jest-extended/all"]` to all my jest config file

One of those config were hidden inline the `package.json` file
